openapi: '3.0.3'
info:
  title: SharpsBack
  version: '1.0'
  contact:
    email: email

  
paths:
  /test:
    get:
      responses:
        '200':
          description: OK

  /user:
    post:
      summary: user signup
      tags:
        - "User"
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/user'
                - type: object
                  properties:
                    password:
                      type: string
              
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/user'
                  token:
                    type: string


components:
  securitySchemes:
    bearerAuth:
      description: Auth token ( Bearer + " " + Value )
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    user:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        avatar:
          type: string
          format: base64
        username:
          type: string
        email:
          type: string
          format: email
