openapi: '3.0.3'
info:
  title: SharpsBack
  version: '1.0'
  contact:
    email: email@email.com

  
paths:
  /test:
    get:
      responses:
        '200':
          description: OK

  /user/signup:
    post:
      summary: user signup
      tags:
        - "User"
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/user'
                - type: object
                  properties:
                    password:
                      type: string  
      responses:
        '201':
          description: A verification email is sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/user'
                  token:
                    type: string

  /user/login:
    post:
      summary: user login
      tags:
        - "User"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: '#/components/schemas/user/properties/email'
                username:
                  $ref: '#/components/schemas/user/properties/username'
                password:
                  type: string
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/user'
                  token:
                    type: string

  /user/logout:
    post:
      summary: logout current session
      tags:
        - "User"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK

  /user/logoutall:
    post:
      summary: logout all sessions
      tags:
        - "User"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK

  /user/resetpassword:
    post:
      summary: request for resetting user password
      tags:
        - "User"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: '#/components/schemas/user/properties/email'
      responses:
        '200':
          description: An email is sent if it's an existing verified email


components:
  securitySchemes:
    bearerAuth:
      description: Auth token ( Bearer + " " + Value )
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    user:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        avatar:
          type: string
          format: base64
        username:
          type: string
        email:
          type: string
          format: email
